### ISSUE TITLE
Evaluation problem

### ISSUE THREAD

**Issue by penut85420** [DRCSolutionService/DRCD#6]
According to the paper:

> F1 score and exact match from Rajpurkar et al. (2016) are used as the evaluation metrics. Both metrics ignore punctuations. In F1 score metric, we consider predictions and ground truth as bag of Chinese character.

Is the ignored punctuations including fullwidth? Is there a original evaluation script for this dataset?

**Comment by DRCKnowledgeTeam** [comment]
we adjust evaluate-v1.1.py. you can find the original version from below
https://github.com/allenai/bi-att-flow/blob/master/squad/evaluate-v1.1.py

In order to evaluate chinese answer, we modify f1_score() function 

we change 
prediction_tokens = normalize_answer(prediction).split()
ground_truth_tokens = normalize_answer(ground_truth).split()
into 
prediction_tokens = normalize_answer(prediction)
ground_truth_tokens = normalize_answer(ground_truth)

and for punctuation, we modify remove_punc() function
we ignore full-width punctuation  "《","》","？","，","。","、","；","："

@penut85420

**Comment by penut85420** [comment]
@DRCKnowledgeTeam really thanks!
